# Problem Set 2 
###  Due September 2, 2025

In [174]:
# Question 1

L = [11, 300, 46, 5]
print(min(L), max(L), (sum(L)/len(L)))

5 300 90.5


In [175]:
# Question 2

#  Integer
int_1 = 3
int_2 = int_1
int_2 = 4
int_1 == int_2

False

In [176]:
# String
str_1 = "hello"
str_2 = str_1
str_2 = "goodbye"
str_1 == str_2

False

In [177]:
# List
list_1 = ["Rose", 3, "Tulip", 5]
list_2 = list_1
list_2[3] = 7
list_1 == list_2

True

In [178]:
# Tuple

tuple_1 = ("Rose", 3, "Tulip", 5)
tuple_2 = tuple_1
tuple_2 += (1,)
tuple_1 == tuple_2

False

In [179]:
# Set 
try:
    set_1 = {"Rose", 3, "Tulip", 5}
    set_2 = set_1   
    set_2[3] = 7
except TypeError:
    set_1 == set_2
pass    
print("This will reaise an error because sets are unordered and do not support indexing.")   


This will reaise an error because sets are unordered and do not support indexing.


In [180]:
# Alternative Set Example
set_2 = set_1
set_2.add("Daisy ") 
print(set_1 == set_2)

True


Question 2 Answers 
   1. Integer: Immutable
   2. String: Immutable
   3. List: Mutable
   4. Tuple: Immutable
   5. Set: Mutable


In [181]:
# Question 3 

a = 3
b = 10
print(a, b)

import Question3 as q

a_sq = q.prod_q3(a,a)
b_sq = q.prod_q3(b,b)
c = q.sum_q3(a_sq, b_sq)
result = q.sqrt_q3(c)
print("The length of the hypotenuse of a triangle, with sides equal to 3 and 10 is", result,".")

3 10
The length of the hypotenuse of a triangle, with sides equal to 3 and 10 is 10.44030650891055 .


## Numpy Chapter Problems (Chp. 4)

In [182]:
import numpy as np
# Question 1 

A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7,], [9, -3, 2, -3]])
print(A)
print(B)

np.dot(A, B)


[[ 3 -1  4]
 [ 1  5 -9]]
[[ 2  6 -5  3]
 [ 5 -8  9  7]
 [ 9 -3  2 -3]]


array([[ 37,  14, -16, -10],
       [-54,  -7,  22,  65]])

In [183]:
# Question 2


Q2_A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
                   
#Clarifying question: Does A^3 mean A*A*A or A^3?

# Assume A^3
Q2_ReturnMatrix =  (- np.linalg.matrix_power(Q2_A, 3))   
+ (9 * (np.dot(Q2_A, Q2_A)))           # 9 * (A^2)
- (15 * Q2_A)                          # 15 * A

print(Q2_ReturnMatrix)


[[ 135 -165 -165]
 [ 348 -402 -387]
 [  78  -72  -57]]


In [184]:
# Question 5

Q5_A = np.array([[0, 2, 4], [1, 3, 5]])
print(Q5_A)
print("************")

Q5_aB = np.full((3,3), 3) #Trying out np.full for funsies
print(Q5_aB)
print("************")

Q5_B = np.tril(Q5_aB) # Making lower triangular matrix
print(Q5_B)

Q5_C = np.diag([-2, -2, -2]) #Trying out np. diag for funsies
print(Q5_C)
print("************")

#Check that matrices were created correctly before proceeding

################### Create monster matrix###################
Q5_11 = np.zeros((3,3))
Q5_12 = Q5_A.T #should be 3x2
Q5_13 = np.eye(3) # Identity matrix 3x3

Q5_row1 = np.hstack((Q5_11, Q5_12, Q5_13)) #3x8

#Verifying first row was done correctly

print(Q5_row1)
print("************")

# Second Row
Q5_21 = Q5_A # A is 2x3
Q5_22 = np.zeros((2,2))
Q5_23 = np.zeros((2,3))

Q5_row2 = np.hstack((Q5_21, Q5_22, Q5_23)) #2x8

#Verifying second row was done correctly
print(Q5_row2)
print("************")

Q5_31 = Q5_B # B is 3x3
Q5_32 = np.zeros((3,2))
Q5_33 = Q5_C # C is 3x3

Q5_row3 = np.hstack((Q5_31, Q5_32, Q5_33))


#Verifying third row was done correctly
print(Q5_row3)
print("************")
Q5_Monster = np.vstack((Q5_row1, Q5_row2, Q5_row3)) 

print(Q5_Monster)

[[0 2 4]
 [1 3 5]]
************
[[3 3 3]
 [3 3 3]
 [3 3 3]]
************
[[3 0 0]
 [3 3 0]
 [3 3 3]]
[[-2  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]
************
[[0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 2. 3. 0. 1. 0.]
 [0. 0. 0. 4. 5. 0. 0. 1.]]
************
[[0. 2. 4. 0. 0. 0. 0. 0.]
 [1. 3. 5. 0. 0. 0. 0. 0.]]
************
[[ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]
************
[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


## Object Oriented Programming (Chp. 4)

In [185]:
# Question 1

class Backpack:
    def __init__(self, name, color, max_size=5):  # Constructor
        self.name = name      # Name attribute
        self.color = color    # Color attribute
        self.max_size = max_size  # Max size attribute
        self.contents = []    # Contents attribute, starts as empty list

    def put(self, item):
        """Add 'item' to the backpack's list of contents."""

        if len(self.contents) >= self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)

    def dump(self):
        """Empty the backpack contents."""
        self.contents = []


# Simple test code for the Backpack class.
def test_backpack():
    testpack = Backpack("Barry", "black")  # Instantiate the object.

    # Test an attribute
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")

    # Add items
    for item in ["pencil", "pen", "paper", "computer", "notebook", "snack"]:
        testpack.put(item)

    print("Contents:", testpack.contents)

    # Test dump
    testpack.dump()
    print("After dump:", testpack.contents)


# Run the test
test_backpack()


No Room!
Contents: ['pencil', 'pen', 'paper', 'computer', 'notebook']
After dump: []


In [186]:
# Question 5

class Jetpack(Backpack):
    """
    Jetpack class that extends Backpack.
    Adds fuel storage and flying ability.
    """

    def __init__(self, name, color, max_size=2, fuel=10):
        """
        Set up a Jetpack with name, color, max_size (default 2), and fuel (default 10).
        """
        super().__init__(name, color, max_size)
        self.fuel = fuel

    def fly(self, fuel_burned):
        """
        Burn fuel to fly.
        If fuel_burned is more than what’s available, print a warning and don’t change fuel.
        """
        if fuel_burned > self.fuel:
            print("Not enough fuel!")
        else:
            self.fuel -= fuel_burned

    def dump(self):
        """
        Clear contents and reset fuel to 0.
        """
        super().dump()
        self.fuel = 0